services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: sh -c "pnpm install && pnpm run start:dev reservations"
    environment:
      - CI=true
      - npm_config_store_dir=/usr/src/app/node_modules/.pnpm-store
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm install && pnpm run start:dev auth"
    environment:
      - CI=true
      - npm_config_store_dir=/usr/src/app/node_modules/.pnpm-store
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: sh -c "pnpm install && pnpm run start:dev payments"
    environment:
      - CI=true
      - npm_config_store_dir=/usr/src/app/node_modules/.pnpm-store
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  # notifications:
  #   build:
  #     context: .
  #     dockerfile: ./apps/notifications/Dockerfile
  #     target: development
  #   command: pnpm run start:dev notifications
  #   env_file:
  #     - ./apps/notifications/.env
  #   volumes:
  #     - .:/usr/src/app
  mongo:
    image: mongo