@host = http://localhost:3000
@id = 6a764084aef999ea0327305c
# paste the Authentication token from the auth login response here:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTkzODhhZDE0NjhlZTBmZTIyOWM2NTYiLCJpYXQiOjE3ODgwNTM2NzgsImV4cCI6MTc4ODA1NzI3OH0.SJqxE9DBjIprTD0LNKosiJWY6mNphSo1YQGEHdMBt0k

### Create reservation
POST {{host}}/reservations
Content-Type: application/json
Cookie: Authentication={{token}}

{
  "startDate": "02-01-2023",
  "endDate": "02-05-2023",
  "placeId": "123",
  "charge": {
    "amount": 5,
    "card": {
      "cvc": "413",
      "exp_month": 12,
      "exp_year": 2027,
      "number": "4242 4242 4242 4242"
    }
  }
}

### Get all reservations
GET {{host}}/reservations

### Get one reservation
GET {{host}}/reservations/{{id}}

### Update reservation
PATCH {{host}}/reservations/{{id}}
Content-Type: application/json

{
  "placeId": "67890"
}

### Delete reservation
DELETE {{host}}/reservations/{{id}}
