@authServiceUrl = http://localhost:3001
### Create user
POST {{authServiceUrl}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!"
}

### Login
POST {{authServiceUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!"
}