@reservationsServiceUrl = http://localhost:3000
@reservationId = 6958b2736dca76d65df427c3

### Get root endpoint
GET {{reservationsServiceUrl}}/

### Create reservation
POST {{reservationsServiceUrl}}/reservations
Content-Type: application/json

{
  "startDate": "12-25-2025",
  "endDate": "12-26-2025",
  "placeId": "123",
  "invoiceId": "123"
}

### Get all reservations
GET {{reservationsServiceUrl}}/reservations

### Get reservation by id
GET {{reservationsServiceUrl}}/reservations/{{reservationId}}

### Update reservation
PATCH {{reservationsServiceUrl}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "startDate": "2026-01-03T00:00:00.000Z",
  "endDate": "2026-01-04T00:00:00.000Z",
  "placeId": "333",
  "invoiceId": "333"
}

### Delete reservation
DELETE {{reservationsServiceUrl}}/reservations/{{reservationId}}
