@reservationsServiceUrl = http://localhost:3000
@reservationId = 69597fc3600b1be607bc0524

### Create reservation
POST {{reservationsServiceUrl}}/reservations
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTVhZTMzNzRiMzgwZTE5NDJmMmI1MmEiLCJpYXQiOjE3Njc5MTA1MDUsImV4cCI6MTc2NzkxNDEwNX0.q9OhfFLt5feqJaEi7fKaJslgJPXSWQ95KOdWZN-vNWk
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc1MzY2MDg5NTg5YWJiY2NkZWU1YTMiLCJpYXQiOjE3NjkyODkzMzAsImV4cCI6MTc2OTI5MjkzMH0.5y6ahBqMeCRZkAKzKtcoNL1cbYUAYZr5lzyOXfcHNvw

{
  "startDate": "12-25-2025",
  "endDate": "12-26-2025",
  "placeId": "123",
  "invoiceId": "123"
}

### Get all reservations
GET {{reservationsServiceUrl}}/reservations

### Get reservation by id
GET {{reservationsServiceUrl}}/reservations/{{reservationId}}

### Update reservation
PATCH {{reservationsServiceUrl}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "startDate": "2026-01-03T00:00:00.000Z",
  "endDate": "2026-01-04T00:00:00.000Z",
  "placeId": "333",
  "invoiceId": "333"
}

### Delete reservation
DELETE {{reservationsServiceUrl}}/reservations/{{reservationId}}
